[package]
name = "kjxlkj-service-terminal"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
kjxlkj-core-types = { path = "../../core/kjxlkj-core-types" }
tokio = { workspace = true }
