[package]
name = "kjxlkj-render"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
kjxlkj-core-types = { path = "../../core/kjxlkj-core-types" }
kjxlkj-core-ui = { path = "../../core/kjxlkj-core-ui" }
crossterm = { workspace = true }
tokio = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
tracing = { workspace = true }
