[package]
name = "kjxlkj-core-mode"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kjxlkj-core-types = { path = "../kjxlkj-core-types" }
serde.workspace = true

