[package]
name = "kjxlkj-auth"
version.workspace = true
edition.workspace = true

[dependencies]
argon2.workspace = true
password-hash.workspace = true
rand_core.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

