[package]
name = "kjxlkj-render"
version = "0.1.0"
edition = "2021"

[dependencies]
kjxlkj-core-types = { path = "../kjxlkj-core-types" }
kjxlkj-core-ui = { path = "../kjxlkj-core-ui" }
compact_str = { workspace = true }
crossterm = { workspace = true }
unicode-width = { workspace = true }
