[package]
name = "kjxlkj-core-text"
version = "0.1.0"
edition = "2021"

[dependencies]
kjxlkj-core-types = { path = "../kjxlkj-core-types" }
ropey = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
