[package]
name = "kjxlkj-services"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kjxlkj-service-fs = { path = "../kjxlkj-service-fs" }
kjxlkj-service-terminal = { path = "../kjxlkj-service-terminal" }

