[package]
name = "kjxlkj-core-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "UI layout for kjxlkj editor"

[dependencies]
kjxlkj-core-types = { path = "../kjxlkj-core-types" }
