[package]
name = "kjxlkj-input"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
crossterm.workspace = true
kjxlkj-core-types = { path = "../../core/kjxlkj-core-types" }
serde.workspace = true

