[package]
name = "kjxlkj-db"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true
kjxlkj-domain = { path = "../../domain/kjxlkj-domain" }

[dev-dependencies]
tokio.workspace = true
kjxlkj-auth = { path = "../../auth/kjxlkj-auth" }

