[package]
name = "kjxlkj-services"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
kjxlkj-core-types = { path = "../kjxlkj-core-types" }
tokio = { workspace = true }
thiserror = { workspace = true }
